import 'dotenv/config';
import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { PrismaClient } from '@prisma/client';
const db = new PrismaClient();
test.afterAll(() => db.$disconnect());
test('admin manages isolated pool configuration without exposing or invoking keys', async ({page}) => {
  const username = `pool_${randomUUID().slice(0,8)}`;
  const headers = { Origin: 'http://localhost:3000' };
  await page.request.post('/api/auth/register', { headers, data: { username, password: 'Pool-ui-test-2026' } });
  expect((await page.request.get('/api/admin/pool')).status()).toBe(403);
  await db.user.update({ where:{username},data:{role:'ADMIN'} });
  await page.goto('/'); await page.getByRole('button',{name:'管理',exact:true}).click();
  await expect(page.getByRole('heading',{name:'账号池与模型线路'})).toBeVisible();
  const info = await page.request.get('/api/admin/pool'); const body = await info.json();
  expect(body.accounts.length).toBeGreaterThanOrEqual(7);
  expect(JSON.stringify(body)).not.toMatch(/sk-[A-Za-z0-9_-]{20}/);
  const newId = `uitest-${randomUUID().slice(0,8)}`;
  await page.getByRole('button',{name:'添加账号',exact:true}).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('标识',{exact:true}).fill(newId);
  await dialog.getByLabel('名称',{exact:true}).fill('UI测试账号');
  await dialog.getByLabel('所属供应商').selectOption('toapis');
  await dialog.getByLabel('密钥环境变量名').fill('POOL_UI_TEST_KEY');
  await dialog.getByLabel('最多同时占用任务').fill('3');
  await dialog.getByRole('button',{name:'保存配置',exact:true}).click();
  await expect(dialog).not.toBeVisible(); await expect(page.getByText('UI测试账号',{exact:true})).toBeVisible();
  const account = await db.providerAccount.findUniqueOrThrow({where:{id:newId}}); expect(account.maxInFlight).toBe(3);
  const unsafe = await page.request.post('/api/admin/pool/accounts',{headers,data:{id:newId,channelId:'toapis',name:'test',secretEnv:'DATABASE_URL',group:'default',enabled:true,maxInFlight:3}});
  expect(unsafe.status()).toBe(400);
  await page.getByLabel('查看模型线路').selectOption('gpt2-quality');
  await expect(page.getByText('预计上游 ¥0.0133/张 · 优先级 0').first()).toBeVisible();
  await page.screenshot({path:'test-results/pool-admin-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/pool-admin-mobile.png',fullPage:true});
  await db.providerAccount.delete({where:{id:newId}}); await db.user.update({where:{username},data:{role:'USER'}});
});
