import 'dotenv/config';
import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import sharp from 'sharp';
import { PrismaClient } from '@prisma/client';
import { cleanup } from '../../src/lib/jobs';
import { queue, redis } from '../../src/lib/queue';
import { db as serviceDb } from '../../src/lib/db';
const db = new PrismaClient();
test.afterAll(async () => { await db.$disconnect(); await serviceDb.$disconnect(); await queue.close(); redis.disconnect(); });
test('reference upload, generation, ownership, expiry and password change', async ({ page, browser }) => {
  const username = `ref_${randomUUID().slice(0, 8)}`; const password = 'Reference-pass-2026';
  const headers = { Origin: 'http://localhost:3000' };
  const register = await page.request.post('/api/auth/register', { headers, data: { username, password } }); expect(register.status()).toBe(201);
  const payment = await (await page.request.post('/api/payments', { headers, data: { amount: 1000, requestKey: randomUUID() } })).json();
  expect((await page.request.post('/api/payments/test-confirm', { headers, data: { id: payment.id } })).ok()).toBe(true);
  const buffer = await sharp({ create: { width: 240, height: 160, channels: 3, background: '#395573' } }).png().toBuffer();
  const upload = await page.request.post('/api/uploads', { headers, multipart: { file: { name: 'reference.png', mimeType: 'image/png', buffer } } }); expect(upload.status()).toBe(201); const asset = await upload.json();
  const other = await browser.newContext({ baseURL: 'http://localhost:3000' });
  expect((await other.request.post('/api/auth/register', { headers, data: { username: `other_${randomUUID().slice(0, 8)}`, password } })).status()).toBe(201);
  expect((await other.request.get(`/api/assets/${asset.id}`)).status()).toBe(404);
  expect((await other.request.get('/api/admin')).status()).toBe(403);
  const foreignQuote = await (await other.request.post('/api/quote', { headers, data: { modelId: 'demo', mode: 'REFERENCE', size: '1024x1024', quality: 'standard', count: 1 } })).json();
  const foreignTask = await other.request.post('/api/tasks', { headers, data: { quoteId: foreignQuote.id, prompt: 'bad', referenceIds: [asset.id], requestKey: randomUUID() } }); expect(foreignTask.status()).toBe(400); expect((await foreignTask.json()).error).toContain('参考图');
  await page.goto('/'); await page.getByLabel('生成模型').selectOption('demo'); await expect(page.getByLabel('生成模型')).toHaveValue('demo'); await page.getByRole('button', { name: '图生图', exact: true }).click();
  await page.locator('input[type=file]').setInputFiles({ name: 'reference.png', mimeType: 'image/png', buffer }); await expect(page.locator('.reference img')).toBeVisible();
  await page.getByLabel('画面描述').fill('参考图构图测试'); await expect(page.getByRole('button', { name: '生成图片', exact: true })).toBeEnabled(); await page.getByRole('button', { name: '生成图片', exact: true }).click();
  await expect(page.locator('.status.succeeded')).toBeVisible({ timeout: 45000 });
  await page.getByRole('button', { name: '文生图', exact: true }).click();
  await page.getByRole('button', { name: '复用', exact: true }).click();
  await expect(page.locator('.reference img')).toBeVisible();
  await expect(page.getByLabel('画面描述')).toHaveValue('参考图构图测试');
  await page.screenshot({ path: 'test-results/reference-result.png', fullPage: true });
  const tasks = await (await page.request.get('/api/tasks')).json(); const task = tasks.tasks[0]; const output = task.assets[0];
  const image = await page.request.get(`/api/assets/${output.id}`); expect(image.ok()).toBe(true); const metadata = await sharp(await image.body()).metadata(); expect(metadata.width).toBe(1024); expect(metadata.height).toBe(1024);
  await db.asset.update({ where: { id: output.id }, data: { expiresAt: new Date(Date.now() - 1) } });
  expect((await page.request.get(`/api/assets/${output.id}`)).status()).toBe(404);
  await db.taskContent.update({ where: { taskId: task.id }, data: { expiresAt: new Date(Date.now() - 1) } });
  await cleanup();
  expect((await db.asset.findUniqueOrThrow({ where: { id: output.id } })).purgedAt).not.toBeNull();
  expect(await db.taskContent.findUnique({ where: { taskId: task.id } })).toBeNull();
  expect(await db.ledger.count({ where: { reference: task.id } })).toBe(2);
  expect((await page.request.get('/api/wallet')).ok()).toBe(true);
  expect((await page.request.post('/api/auth/password', { headers, data: { currentPassword: password, password: 'New-reference-pass-2026' } })).ok()).toBe(true);
  expect((await page.request.post('/api/quote', { headers: { Origin: 'https://untrusted.example' }, data: {} })).status()).toBe(403);
  // Verify admin UI with a suite-owned account and test-money refund.
  const anotherPayment = await (await page.request.post('/api/payments', { headers, data: { amount: 1000, requestKey: randomUUID() } })).json();
  await page.request.post('/api/payments/test-confirm', { headers, data: { id: anotherPayment.id } });
  const refund = await page.request.post('/api/refunds', { headers, data: { paymentId: payment.id } }); expect(refund.ok()).toBe(true);
  await db.user.update({ where: { username }, data: { role: 'ADMIN' } });
  await page.goto('/'); await page.getByRole('button', { name: '管理', exact: true }).click();
  await expect(page.getByRole('heading', { name: '退款审核' })).toBeVisible();
  await page.getByRole('button', { name: '批准退款', exact: true }).click();
  await expect(page.getByText('没有待处理的退款')).toBeVisible();
  await page.screenshot({ path: 'test-results/admin-desktop.png', fullPage: true });
  await db.user.update({ where: { username }, data: { role: 'USER' } });
  await other.close();
});
