import 'dotenv/config';
import { randomUUID } from 'node:crypto';
import { afterAll, describe, expect, it } from 'vitest';
import { db } from '../../src/lib/db';
import { createTask, quote, settleTask } from '../../src/lib/generation';
import { confirmTestPayment, requestRefund, reviewRefund } from '../../src/lib/payments';
import { redis, queue } from '../../src/lib/queue';
import { monitor } from '../../src/lib/jobs';
const users: string[] = [];
async function account(amount: number) { const u = await db.user.create({ data: { username: `it_${randomUUID().slice(0, 12)}`, passwordHash: 'not-a-login-account', recoveryHash: 'not-a-login-account' } }); users.push(u.id); await db.wallet.create({ data: { userId: u.id, available: amount } }); return u.id; }
async function newQuote(userId: string, count = 1) { return quote(userId, { modelId: 'demo', mode: 'TEXT', size: '1024x1024', quality: 'standard', count }); }
describe('transactional billing on PostgreSQL', () => {
  it('allows only one concurrent spend when balance covers one', async () => { const u = await account(10); const [a,b] = await Promise.all([newQuote(u), newQuote(u)]); const results = await Promise.allSettled([a,b].map(q => createTask(u, { quoteId: q.id, prompt: 'test', requestKey: randomUUID() }))); expect(results.filter(r => r.status === 'fulfilled')).toHaveLength(1); expect(await db.wallet.findUnique({ where: { userId: u } })).toMatchObject({ available: 0, frozen: 10 }); });
  it('settles partial output exactly once under concurrent retries', async () => { const u = await account(100); const q = await newQuote(u, 4); const t = await createTask(u, { quoteId: q.id, prompt: 'test', requestKey: randomUUID() }); await Promise.all([settleTask(t.id, 2), settleTask(t.id, 2)]); expect(await db.wallet.findUnique({ where: { userId: u } })).toMatchObject({ available: 80, frozen: 0 }); expect(await db.ledger.count({ where: { eventKey: `settle:${t.id}` } })).toBe(1); });
  it('deduplicates a submitted quote and creates an outbox entry atomically', async () => { const u = await account(100); const q = await newQuote(u); const p = { quoteId: q.id, prompt: 'test', requestKey: randomUUID() }; const a = await createTask(u, p); const b = await createTask(u, p); expect(a.id).toBe(b.id); expect(await db.outbox.count({ where: { taskId: a.id } })).toBe(1); });
  it('refuses a foreign quote', async () => { const a = await account(100); const b = await account(100); const q = await newQuote(a); await expect(createTask(b, { quoteId: q.id, prompt: 'test', requestKey: randomUUID() })).rejects.toThrow(); });
  it('credits duplicate callbacks only once and refunds only once', async () => { const u = await account(0); const p = await db.payment.create({ data: { userId: u, requestKey: randomUUID(), provider: 'TEST', amount: 1000 } }); await Promise.all([confirmTestPayment(u, p.id), confirmTestPayment(u, p.id)]); expect((await db.wallet.findUniqueOrThrow({ where: { userId: u } })).available).toBe(1000); const r = await requestRefund(u, p.id); await Promise.all([reviewRefund('test-admin', r.id, true), reviewRefund('test-admin', r.id, true)]); expect(await db.wallet.findUnique({ where: { userId: u } })).toMatchObject({ available: 0, frozen: 0 }); });
  it('releases rejected refund holds', async () => { const u = await account(0); const p = await db.payment.create({ data: { userId: u, requestKey: randomUUID(), provider: 'TEST', amount: 1000 } }); await confirmTestPayment(u, p.id); const r = await requestRefund(u, p.id); await reviewRefund('test-admin', r.id, false); expect(await db.wallet.findUnique({ where: { userId: u } })).toMatchObject({ available: 1000, frozen: 0 }); });
  it('rebuilds a lost queue entry from database truth without a second hold', async () => { const u = await account(100); const q = await newQuote(u); const t = await createTask(u, { quoteId: q.id, prompt: 'queue recovery test', requestKey: randomUUID() }); await db.task.update({ where: { id: t.id }, data: { createdAt: new Date(Date.now() - 120000) } }); await db.outbox.update({ where: { taskId: t.id }, data: { sentAt: new Date() } }); await monitor(); expect(await queue.getJob(t.id)).not.toBeNull(); await (await queue.getJob(t.id))!.remove(); await monitor(); expect(await queue.getJob(t.id)).not.toBeNull(); expect(await db.ledger.count({ where: { eventKey: `hold:${t.id}` } })).toBe(1); });
});
afterAll(async () => { // Delete only accounts created by this suite, never clear shared tables.
  const tasks = await db.task.findMany({ where: { userId: { in: users } }, select: { id: true } }); const ids = tasks.map(t => t.id);
  for (const id of ids) { const job = await queue.getJob(id); if (job) await job.remove(); }
  await db.outbox.deleteMany({ where: { taskId: { in: ids } } }); await db.taskContent.deleteMany({ where: { taskId: { in: ids } } }); await db.task.deleteMany({ where: { userId: { in: users } } }); await db.quote.deleteMany({ where: { userId: { in: users } } }); await db.refund.deleteMany({ where: { userId: { in: users } } }); await db.payment.deleteMany({ where: { userId: { in: users } } }); await db.ledger.deleteMany({ where: { userId: { in: users } } }); await db.wallet.deleteMany({ where: { userId: { in: users } } }); await db.user.deleteMany({ where: { id: { in: users } } }); await queue.close(); redis.disconnect(); await db.$disconnect(); });
