'use client';
import { useEffect, useState, type FormEvent } from 'react';
import { Plus, RefreshCw, Settings2, X } from 'lucide-react';
import * as Dialog from '@radix-ui/react-dialog';
import { poolAdapters } from '@/lib/pool-types';

type Channel = { id: string; name: string; baseUrl: string | null; adapter: string; enabled: boolean };
type Account = { id: string; channelId: string; name: string; secretEnv: string; group: string; enabled: boolean; maxInFlight: number; hasKey: boolean; inFlight: number; cooldownUntil: string | null; lastError: string | null; checkedAt: string | null; modelCount: number | null };
type Model = { id: string; name: string; sizes: string[]; qualities: string[]; maxReferences: number };
type Route = { id: string; modelId: string; channelId: string; upstreamModel: string; adapter: string; mode: string; size: string; quality: string; requiredGroup: string; costMicros: number; priority: number; maxReferences: number; enabled: boolean; priceNote: string; params: { ratio?: string; resolution?: string } };
type Pool = { channels: Channel[]; accounts: Account[]; routes: Route[]; models: Model[] };
type Editor = { kind: 'accounts'; item?: Account } | { kind: 'channels'; item?: Channel } | { kind: 'routes'; item?: Route };
async function api<T>(path: string, data?: unknown): Promise<T> { const r = await fetch(`/api/admin/pool${path}`, { method: data === undefined ? 'GET' : 'POST', headers: { 'Content-Type': 'application/json' }, body: data === undefined ? undefined : JSON.stringify(data) }); const value = await r.json(); if (!r.ok) throw new Error(value.error || '操作失败'); return value; }
export default function PoolAdmin({ onChange }: { onChange: () => Promise<void> }) {
  const [data, setData] = useState<Pool | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [editor, setEditor] = useState<Editor | null>(null); const [filter, setFilter] = useState('');
  async function reload() { setData(await api<Pool>('')); }
  useEffect(() => { void reload().catch(() => setMessage('号池加载失败，请刷新')); }, []);
  async function run(fn: () => Promise<void>) { setBusy(true); setMessage(''); try { await fn(); await reload(); await onChange(); } catch (e) { setMessage(e instanceof Error ? e.message : '操作失败'); } finally { setBusy(false); } }
  function save(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); if (!editor) return; const fd = new FormData(e.currentTarget); const s = (k: string) => String(fd.get(k) || ''); const n = (k: string) => Number(fd.get(k));
    const common = { id: s('id'), enabled: fd.get('enabled') === 'on' };
    const payload = editor.kind === 'accounts' ? { ...common, name: s('name'), channelId: s('channelId'), secretEnv: s('secretEnv'), group: s('group'), maxInFlight: n('maxInFlight') } : editor.kind === 'channels' ? { ...common, name: s('name'), baseUrl: s('baseUrl'), adapter: s('adapter') } : { ...common, modelId: s('modelId'), channelId: s('channelId'), upstreamModel: s('upstreamModel'), adapter: s('adapter'), mode: s('mode'), size: s('size'), quality: s('quality'), requiredGroup: s('requiredGroup'), costMicros: Math.round(n('cost') * 1e6), priority: n('priority'), maxReferences: n('maxReferences'), priceNote: s('priceNote'), params: { resolution: s('resolution'), ratio: s('ratio') } };
    void run(async () => { await api(`/${editor.kind}`, payload); setEditor(null); setMessage('配置已保存；已提交任务保持原线路'); });
  }
  if (!data) return <section className="surface table-section"><h2>账号池</h2><p role="status">{message || '正在加载账号池…'}</p></section>;
  const item = editor?.item;
  return <section className="surface table-section pool-section">
    <div className="row between"><div><h2>账号池与模型线路</h2><p>按规格选择可用低价线路；结果不明时保留原任务，不重复生图。</p></div><button className="secondary" disabled={busy} onClick={() => void run(reload)} aria-label="刷新号池"><RefreshCw size={16}/></button></div>
    {message && <p role="status" className="pool-message">{message}</p>}
    <div className="pool-summary"><span>供应商 <b>{data.channels.length}</b></span><span>密钥已就绪 <b>{data.accounts.filter(a => a.hasKey).length}/{data.accounts.length}</b></span><span>占用任务 <b>{data.accounts.reduce((n,a) => n+a.inFlight,0)}</b></span></div>
    <div className="row pool-actions"><button className="secondary" disabled={busy} onClick={() => setEditor({ kind: 'accounts' })}><Plus size={15}/>添加账号</button><button className="secondary" disabled={busy} onClick={() => setEditor({ kind: 'channels' })}><Plus size={15}/>添加供应商</button><button className="secondary" disabled={busy} onClick={() => setEditor({ kind: 'routes' })}><Plus size={15}/>添加线路</button></div>
    {data.channels.map(c => <div className="pool-provider" key={c.id}>
      <div className="row between"><b>{c.name}{!c.enabled && ' · 已停用'}</b><button className="text-button" disabled={busy} onClick={() => setEditor({ kind: 'channels', item: c })} aria-label={`编辑供应商 ${c.name}`}><Settings2 size={15}/>设置</button></div>
      {data.accounts.filter(a => a.channelId === c.id).map(a => <div className="order-row" key={a.id}><div><b>{a.name}</b><small>{!a.enabled ? '已停用' : !a.hasKey ? '待配置密钥' : a.cooldownUntil && new Date(a.cooldownUntil) > new Date() ? '冷却中' : '密钥就绪'} · {a.group}组 · {a.inFlight}/{a.maxInFlight} 占用</small><small>{a.checkedAt ? `鉴权已通过 · ${a.modelCount}个模型` : '未检查鉴权'}{a.lastError ? ` · ${a.lastError}` : ''}</small></div><div className="row"><button className="secondary" disabled={busy || !a.hasKey} onClick={() => void run(async () => { const r = await api<{ message: string }>('/check', { id: a.id }); setMessage(r.message); })}>检查连接</button><button className="secondary" disabled={busy} onClick={() => setEditor({ kind: 'accounts', item: a })}>编辑</button></div></div>)}
    </div>)}
    <label className="pool-filter">查看模型线路<select value={filter} onChange={e => setFilter(e.target.value)}><option value="">选择模型</option>{data.models.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label>
    {filter && <div className="pool-route-list">{data.routes.filter(r => r.modelId === filter).map(r => <div className="order-row" key={r.id}><div><b>{data.channels.find(c => c.id === r.channelId)?.name} · {r.requiredGroup}</b><small>{r.mode === 'TEXT' ? '文生图' : '参考图'} · {r.size} · {r.quality} · {r.enabled ? '已启用' : '停用'}</small><small>预计上游 ¥{(r.costMicros/1e6).toFixed(4)}/张 · 优先级 {r.priority}</small></div><button className="secondary" disabled={busy} onClick={() => setEditor({ kind: 'routes', item: r })}>编辑线路</button></div>)}</div>}
    <p className="pool-footnote">成本为估算，不等于网站售价。分组必须与上游令牌设置一致；没有对应分组账号的优惠线路不会使用。检查连接仅查询模型，不产生生图费用。</p>
    <Dialog.Root open={!!editor} onOpenChange={v => !v && setEditor(null)}><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="dialog pool-dialog" aria-describedby={undefined}><div className="dialog-head"><Dialog.Title>{editor?.kind === 'accounts' ? '账号设置' : editor?.kind === 'channels' ? '供应商设置' : '模型线路设置'}</Dialog.Title><Dialog.Close className="icon-button" aria-label="关闭号池设置"><X size={20}/></Dialog.Close></div>
      {editor && <form className="stack-form" onSubmit={save} key={`${editor.kind}-${item?.id || 'new'}`}>
        <label>标识<input name="id" defaultValue={item?.id || `${editor.kind}-${Date.now()}`} readOnly={!!item} required/></label>
        {editor.kind !== 'routes' && <label>名称<input name="name" defaultValue={editor.item?.name} required maxLength={80}/></label>}
        {editor.kind !== 'channels' && <label>所属供应商<select name="channelId" defaultValue={editor.item?.channelId || data.channels[0]?.id}>{data.channels.map(c => <option value={c.id} key={c.id}>{c.name}</option>)}</select></label>}
        {editor.kind === 'accounts' && <><label>密钥环境变量名<input name="secretEnv" defaultValue={editor.item?.secretEnv || 'POOL_PROVIDER_2_KEY'} pattern="POOL_[A-Z0-9_]+_KEY" required/></label><p>填写服务端变量名，不要粘贴密钥。现有两把密钥由本机文件读取。</p><label>上游令牌分组<input name="group" defaultValue={editor.item?.group || 'default'} required/></label><label>最多同时占用任务<input name="maxInFlight" type="number" min={1} max={100} defaultValue={editor.item?.maxInFlight || 2} required/></label></>}
        {editor.kind === 'channels' && <label>API 根地址<input name="baseUrl" type="url" defaultValue={editor.item?.baseUrl || 'https://'} required/></label>}
        {editor.kind !== 'accounts' && <label>接口协议<select name="adapter" defaultValue={editor.item?.adapter || 'toapis-images'}>{poolAdapters.map(a => <option key={a} value={a}>{a}</option>)}</select></label>}
        {editor.kind === 'routes' && <><label>模型<select name="modelId" defaultValue={editor.item?.modelId || filter}>{data.models.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>上游模型 ID<input name="upstreamModel" defaultValue={editor.item?.upstreamModel} required/></label><div className="pool-form-grid"><label>模式<select name="mode" defaultValue={editor.item?.mode || 'TEXT'}><option value="TEXT">文生图</option><option value="REFERENCE">参考图</option></select></label><label>分组<input name="requiredGroup" defaultValue={editor.item?.requiredGroup || 'default'} required/></label><label>像素规格<input name="size" defaultValue={editor.item?.size || '1024x1024'} required/></label><label>质量<input name="quality" defaultValue={editor.item?.quality || 'standard'} required/></label><label>分辨率档<select name="resolution" defaultValue={editor.item?.params.resolution || '1K'}>{['1K','2K','3K','4K'].map(r => <option key={r}>{r}</option>)}</select></label><label>比例<input name="ratio" defaultValue={editor.item?.params.ratio || '1:1'} required/></label><label>成本（元/张）<input name="cost" type="number" min={.000001} step={.000001} defaultValue={editor.item ? editor.item.costMicros/1e6 : .2} required/></label><label>优先级（越小越优先）<input name="priority" type="number" min={0} max={100} defaultValue={editor.item?.priority || 0} required/></label><label>最多参考图<input name="maxReferences" type="number" min={0} max={8} defaultValue={editor.item?.maxReferences || 0} required/></label></div><label>价格备注<input name="priceNote" defaultValue={editor.item?.priceNote || ''}/></label></>}
        <label className="pool-check"><input name="enabled" type="checkbox" defaultChecked={item?.enabled ?? true}/>启用此配置</label><p role="alert">{message}</p><button className="primary" disabled={busy}>{busy ? '正在保存…' : '保存配置'}</button>
      </form>}
    </Dialog.Content></Dialog.Portal></Dialog.Root>
  </section>;
}
