'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import PoolAdmin from './pool-admin';
import { Aperture, ImagePlus, Images, Wallet, Settings2, ShieldCheck, ArrowUpRight, Plus, X, Download, RefreshCw, Sparkles, ChevronDown, LogOut, Upload, Check, Clock3, CircleHelp, PanelLeftClose, LockKeyhole, Copy, Trash2, LoaderCircle, SlidersHorizontal } from 'lucide-react';

type Price = { id: string; mode: string; size: string; quality: string; unitCents: number };
type Model = { id: string; name: string; family: string; enabled: boolean; available: boolean; sizes: string[]; qualities: string[]; maxCount: number; maxReferences: number; prices: Price[] };
type Asset = { id: string; width: number; height: number; expiresAt: string };
type Task = { id: string; modelId: string; modelName: string; status: string; mode: string; size: string; quality: string; count: number; deliveredCount: number; unitCents: number; createdAt: string; prompt: string | null; assets: Asset[]; referenceIds: string[]; referenceAssets?: Asset[]; error?: string };
type User = { id: string; username: string; role: string };
type Balance = { available: number; frozen: number };
type Payment = { id: string; amount: number; status: string; createdAt: string };
type Ledger = { id: string; kind: string; availableDelta: number; frozenDelta: number; reference: string; createdAt: string };
type Refund = { id: string; paymentId: string; amount: number; status: string };
type AdminData = { models: Model[]; channels: { id: string; name: string; enabled: boolean; verified: boolean }[]; refunds: Refund[]; tasks: Task[] };
const placeholders: Model[] = ['GPT Image', 'Gemini', 'Grok', 'Seedream'].map((name, i) => ({ id: ['gpt', 'gemini', 'grok', 'seedream'][i], name, family: name, enabled: false, available: false, sizes: [], qualities: [], maxCount: 1, maxReferences: 0, prices: [] }));
const cash = (value = 0) => `¥${(value / 100).toFixed(2)}`;
const time = (value: string) => new Date(value).toLocaleString('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hour12: false });
const states: Record<string, string> = { QUEUED: '等待生成', RUNNING: '正在生成', SAVING: '保存结果', PENDING: '上游处理中', REVIEW: '待核查', SUCCEEDED: '已完成', PARTIAL: '部分完成', FAILED: '生成失败' };
const ledgerNames: Record<string, string> = { GENERATION_HOLD: '生成预留', GENERATION_SETTLED: '生成结算', TEST_TOPUP: '测试充值（无真实支付）', REFUND_HOLD: '退款预留', REFUND_RELEASE: '退款驳回释放', TEST_REFUND: '测试退款' };
async function api<T>(path: string, body?: unknown, method?: string): Promise<T> {
  const res = await fetch(`/api/${path}`, { method: method || (body === undefined ? 'GET' : 'POST'), headers: body instanceof FormData ? {} : { 'Content-Type': 'application/json' }, body: body === undefined ? undefined : body instanceof FormData ? body : JSON.stringify(body), cache: 'no-store' });
  const data = await res.json(); if (!res.ok) throw new Error(data.error || '请求失败'); return data;
}
function Modal({ open, onOpenChange, title, children }: { open: boolean; onOpenChange: (v: boolean) => void; title: string; children: React.ReactNode }) {
  return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="dialog" aria-describedby={undefined}><div className="dialog-head"><Dialog.Title>{title}</Dialog.Title><Dialog.Close className="icon-button" aria-label="关闭"><X size={20}/></Dialog.Close></div>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>;
}
export default function Studio() {
  const [tab, setTab] = useState('studio'); const [user, setUser] = useState<User | null>(null); const [balance, setBalance] = useState<Balance>({ available: 0, frozen: 0 });
  const [models, setModels] = useState<Model[]>(placeholders); const [modelId, setModelId] = useState('gpt'); const [mode, setMode] = useState('TEXT');
  const [size, setSize] = useState(''); const [quality, setQuality] = useState(''); const [count, setCount] = useState(1); const [prompt, setPrompt] = useState(''); const [refs, setRefs] = useState<Asset[]>([]);
  const [tasks, setTasks] = useState<Task[]>([]); const [quote, setQuote] = useState<{ id: string; unitCents: number } | null>(null); const [busy, setBusy] = useState(false); const [uploading, setUploading] = useState(false);
  const [demo, setDemo] = useState(false); const [notice, setNotice] = useState(''); const [serviceError, setServiceError] = useState('');
  const [auth, setAuth] = useState(false); const [authMode, setAuthMode] = useState('login'); const [recovery, setRecovery] = useState(''); const [authError, setAuthError] = useState('');
  const [preview, setPreview] = useState<Asset | null>(null); const [ledger, setLedger] = useState<Ledger[]>([]); const [payments, setPayments] = useState<Payment[]>([]); const [refunds, setRefunds] = useState<Refund[]>([]); const [topup, setTopup] = useState(1000);
  const [admin, setAdmin] = useState<AdminData | null>(null); const [priceEdit, setPriceEdit] = useState<{ model: Model; price: Price } | null>(null); const [help, setHelp] = useState(false);
  const fileInput = useRef<HTMLInputElement>(null); const requestKey = useRef<string | null>(null);
  const pendingReuse = useRef<Task | null>(null);
  const selected = models.find(m => m.id === modelId) || models[0];
  const refreshUser = useCallback(async () => { const d = await api<{ user: User | null; wallet?: Balance; demo: boolean }>('me'); setUser(d.user); setBalance(d.wallet || { available: 0, frozen: 0 }); setDemo(d.demo); return d.user; }, []);
  const refreshTasks = useCallback(async () => { const d = await api<{ tasks: Task[] }>('tasks'); setTasks(d.tasks); }, []);
  const refreshWallet = useCallback(async () => { const d = await api<{ wallet: Balance; ledger: Ledger[]; payments: Payment[]; refunds: Refund[] }>('wallet'); setBalance(d.wallet); setLedger(d.ledger); setPayments(d.payments); setRefunds(d.refunds); }, []);
  const refreshAdmin = useCallback(async () => setAdmin(await api<AdminData>('admin')), []);
  const run = async (action: () => Promise<void>) => { setBusy(true); try { await action(); } catch (e) { setNotice((e as Error).message); } finally { setBusy(false); } };
  const loadModels = useCallback(async () => { const d = await api<{ models: Model[]; demo: boolean }>('models'); setModels(d.models); setDemo(d.demo); setModelId(id => d.models.some(m => m.id === id && m.available) ? id : d.models.find(m => m.available)?.id || id); }, []);
  useEffect(() => { Promise.all([loadModels(), refreshUser()]).then(() => setServiceError('')).catch(() => setServiceError('服务尚未就绪，暂时无法登录或生成。请稍后刷新。')); }, [loadModels, refreshUser]);
  useEffect(() => { if (!user) { setTasks([]); return; } refreshTasks().catch(e => setNotice(e.message)); }, [user, refreshTasks]);
  useEffect(() => { if (!user) return; if (tab === 'wallet') refreshWallet().catch(e => setNotice(e.message)); if (tab === 'admin') refreshAdmin().catch(e => setNotice(e.message)); }, [tab, user, refreshWallet, refreshAdmin]);
  useEffect(() => { if (!user || !tasks.some(t => ['QUEUED', 'RUNNING', 'SAVING', 'PENDING'].includes(t.status))) return; const timer = setInterval(() => { Promise.all([refreshTasks(), refreshUser()]).catch(() => {}); }, 3500); return () => clearInterval(timer); }, [tasks, user, refreshTasks, refreshUser]);
  useEffect(() => { const t = pendingReuse.current; if (t && t.modelId === modelId) { restoreParameters(t); pendingReuse.current = null; } else { setSize(selected?.sizes[0] || ''); setQuality(selected?.qualities[0] || ''); setCount(1); setRefs([]); } setQuote(null); }, [modelId]);
  useEffect(() => { if (!size && selected?.sizes.length) setSize(selected.sizes[0]); if (!quality && selected?.qualities.length) setQuality(selected.qualities[0]); }, [selected, size, quality]);
  useEffect(() => { let active = true; setQuote(null); requestKey.current = null; if (user && selected?.available && size && quality) api<{ id: string; unitCents: number }>('quote', { modelId, mode, size, quality, count }).then(q => { if (active) setQuote(q); }).catch(e => { if (active) setNotice(e.message); }); return () => { active = false; }; }, [user?.id, modelId, mode, size, quality, count, selected?.available]);
  useEffect(() => { if (!notice) return; const t = setTimeout(() => setNotice(''), 6000); return () => clearTimeout(t); }, [notice]);
  async function submitAuth(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault(); const form = new FormData(e.currentTarget); setBusy(true); setAuthError('');
    try { const d = await api<{ recoveryCode?: string }>(`auth/${authMode}`, Object.fromEntries(form)); if (d.recoveryCode) setRecovery(d.recoveryCode); else setAuth(false); await refreshUser(); }
    catch (e) { setAuthError((e as Error).message); } finally { setBusy(false); }
  }
  async function upload(files: FileList | File[]) {
    if (!user) { setAuth(true); return; } if (!selected.available) { setNotice('当前模型尚未开放'); return; }
    const remaining = selected.maxReferences - refs.length; if (files.length > remaining) { setNotice(`该模型最多支持 ${selected.maxReferences} 张参考图`); return; }
    setUploading(true); try { for (const file of Array.from(files)) { const f = new FormData(); f.set('file', file); const a = await api<Asset>('uploads', f); setRefs(r => [...r, a]); } } catch (e) { setNotice((e as Error).message); } finally { setUploading(false); }
  }
  async function generate() {
    if (!user) { setAuth(true); return; } if (!quote) return;
    await run(async () => { requestKey.current ||= crypto.randomUUID(); await api('tasks', { quoteId: quote.id, prompt, referenceIds: mode === 'REFERENCE' ? refs.map(a => a.id) : [], requestKey: requestKey.current }); await Promise.all([refreshTasks(), refreshUser()]); setQuote(await api('quote', { modelId, mode, size, quality, count })); requestKey.current = null; setNotice('任务已提交，离开页面也会继续处理'); });
  }
  function restoreParameters(t: Task) { const m = models.find(m => m.id === t.modelId); setMode(t.mode); setPrompt(t.prompt || ''); setSize(m?.sizes.includes(t.size) ? t.size : m?.sizes[0] || ''); setQuality(m?.qualities.includes(t.quality) ? t.quality : m?.qualities[0] || ''); setCount(Math.min(t.count, m?.maxCount || 1)); setRefs((t.referenceAssets || []).filter(a => new Date(a.expiresAt) > new Date()).slice(0, m?.maxReferences || 0)); }
  function reuse(t: Task) { if (t.modelId === modelId) restoreParameters(t); else { pendingReuse.current = t; setModelId(t.modelId); } setTab('studio'); setNotice('已复用当前仍有效的参数和参考图，请确认后生成'); }
  const nav = [{ id: 'studio', icon: ImagePlus, name: '创作' }, { id: 'history', icon: Images, name: '历史' }, { id: 'wallet', icon: Wallet, name: '钱包' }, { id: 'account', icon: Settings2, name: '账户' }];
  const price = quote?.unitCents ?? selected?.prices.find(p => p.mode === mode && p.size === size && p.quality === quality)?.unitCents;
  const title = ({ studio: '图片创作', history: '创作历史', wallet: '我的钱包', account: '账户设置', admin: '管理工作台' } as Record<string, string>)[tab];
  function resultCard(t: Task) {
    return <article className="result-card" key={t.id}><div className="result-meta"><span className="model-dot"/>{t.modelName}<span className={`status ${t.status.toLowerCase()}`}>{states[t.status]}</span></div>
      {t.assets.length ? <div className={`image-grid count-${t.assets.length}`}>{t.assets.map(a => <div className="image-tile" key={a.id}><button className="image-open" onClick={() => setPreview(a)} aria-label="查看大图"><img src={`/api/assets/${a.id}`} alt={t.prompt || '生成结果'} loading="lazy"/></button><a className="download-float" href={`/api/assets/${a.id}?download`} aria-label="下载图片"><Download size={18}/></a></div>)}</div> : <div className="pending-image">{['FAILED', 'REVIEW'].includes(t.status) ? <CircleHelp size={30}/> : <LoaderCircle className="spin" size={30}/>}<span>{states[t.status]}</span>{t.error && <p>{t.error}</p>}</div>}
      <div className="result-footer"><p>{t.prompt || '提示词已过期'}</p>{t.referenceIds.length > 0 && <div className="history-references"><span>参考图</span>{t.referenceIds.map(id => <a key={id} href={`/api/assets/${id}?download`} aria-label="下载参考图"><img src={`/api/assets/${id}`} alt="历史参考图"/></a>)}</div>}<div className="row between"><span>{t.size.replace('x', ' × ')} <span className="dot-separator">·</span> {time(t.createdAt)}</span><button className="text-button" onClick={() => reuse(t)} disabled={!t.prompt}><RefreshCw size={14}/>复用</button></div>{t.assets[0] && <div className="expiry"><Clock3 size={12}/>保留至 {time(t.assets[0].expiresAt)}<button className="text-button danger" onClick={() => run(async () => { for (const a of t.assets) await api(`assets/${a.id}`, undefined, 'DELETE'); await refreshTasks(); })}>删除图片</button></div>}</div></article>;
  }
  return <div className="app-shell">
    <aside className="nav-rail"><a href="/" className="brand" aria-label="幻彩首页"><Aperture size={30}/></a><nav>{nav.map(n => <button key={n.id} className={`nav-item ${tab === n.id ? 'active' : ''}`} onClick={() => setTab(n.id)}><n.icon size={21}/><span>{n.name}</span></button>)}{user?.role === 'ADMIN' && <button className={`nav-item ${tab === 'admin' ? 'active' : ''}`} onClick={() => setTab('admin')}><ShieldCheck size={21}/><span>管理</span></button>}</nav><button className="nav-item help-button" onClick={() => setHelp(true)}><CircleHelp size={20}/><span>帮助</span></button><button className="avatar" onClick={() => user ? setTab('account') : setAuth(true)} aria-label={user ? '账户设置' : '登录'}>{user?.username[0]?.toUpperCase() || <LockKeyhole size={17}/>}</button></aside>
    <div className="main-shell"><header className="topbar"><div className="wordmark">幻彩<span>HUANCAI STUDIO</span></div><div className="top-actions">{demo && <span className="test-badge">测试环境 · 无真实支付</span>}<button className="balance-pill" onClick={() => setTab('wallet')}><Wallet size={15}/>{cash(balance.available)}<Plus size={14}/></button>{user ? <button className="user-button" onClick={() => setTab('account')}>{user.username}</button> : <button className="login-button" onClick={() => setAuth(true)}>登录 / 注册<ArrowUpRight size={16}/></button>}</div></header>
      {serviceError && <div className="service-banner" role="status">{serviceError}<button onClick={() => location.reload()}>刷新</button></div>}
      {tab === 'studio' ? <main className="studio-layout"><section className="control-panel"><div className="panel-title"><h1>{title}</h1><SlidersHorizontal size={18}/></div><div className="segmented"><button className={mode === 'TEXT' ? 'selected' : ''} onClick={() => setMode('TEXT')}><Sparkles size={15}/>文生图</button><button className={mode === 'REFERENCE' ? 'selected' : ''} onClick={() => setMode('REFERENCE')}><ImagePlus size={15}/>图生图</button></div>
        <div className="field"><label htmlFor="model">生成模型</label><div className="select-wrap"><span className="model-symbol"><Aperture size={19}/></span><select id="model" value={modelId} onChange={e => setModelId(e.target.value)}>{models.map(m => <option key={m.id} value={m.id}>{m.name}{m.available ? '' : ' · 待接入'}</option>)}</select><ChevronDown size={16}/></div><div className="model-note"><span className={`tiny-dot ${selected?.available ? 'online' : ''}`}/>{selected?.available ? selected.family === 'TEST' ? '本地流程测试图，不调用 AI' : '接口已配置，生成将消耗上游额度' : '模型入口预留，暂未开放'}</div></div>
        {mode === 'REFERENCE' && <div className="field"><label>参考图片 <span>{refs.length} / {selected.maxReferences || '—'}</span></label><div className="reference-list">{refs.map(a => <div className="reference" key={a.id}><img src={`/api/assets/${a.id}`} alt="上传的参考图"/><button onClick={() => setRefs(r => r.filter(x => x.id !== a.id))} aria-label="移除参考图"><X size={13}/></button></div>)}</div><button className="upload-zone" disabled={uploading || !selected.available} onClick={() => fileInput.current?.click()} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); if (!uploading) void upload(e.dataTransfer.files); }}>{uploading ? <LoaderCircle className="spin" size={22}/> : <Upload size={22}/>}<span>拖入图片，或点击上传</span><small>PNG、JPG、WebP · 最大 20 MB</small></button><input hidden ref={fileInput} type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={e => { if (e.target.files) void upload(e.target.files); e.target.value = ''; }}/></div>}
        <div className="field"><label htmlFor="prompt">画面描述<button className="text-button" onClick={() => setPrompt('')} disabled={!prompt}>清空</button></label><div className="prompt-wrap"><textarea id="prompt" value={prompt} maxLength={4000} onChange={e => setPrompt(e.target.value)} placeholder={mode === 'TEXT' ? '描述你想看到的画面，试着加入主体、光线、构图和风格…' : '描述你希望对参考图片做出的改变…'}/><span className="char-count">{prompt.length} / 4000</span></div></div>
        <div className="field"><label htmlFor="size">画面尺寸<span>模型原生</span></label>{selected.sizes.length ? <div className="size-options">{selected.sizes.map(s => { const [w, h] = s.split('x').map(Number); return <button key={s} className={size === s ? 'selected' : ''} onClick={() => setSize(s)}><span className="ratio-icon" style={{ width: w >= h ? 22 : 16, height: w <= h ? 22 : 16 }}/><span>{w === h ? '1:1' : w > h ? '3:2' : '2:3'}</span><small>{s.replace('x', ' × ')}</small></button>; })}</div> : <div className="unavailable-field">接入后显示支持的原生尺寸</div>}</div>
        <div className="field"><label htmlFor="quality">生成质量</label><select id="quality" value={quality} onChange={e => setQuality(e.target.value)} disabled={!selected.qualities.length}>{selected.qualities.length ? selected.qualities.map(q => <option key={q} value={q}>{({ standard: '标准', auto: '自动', low: '草稿（省钱）', medium: '均衡', high: '精细' } as Record<string, string>)[q] || q}</option>) : <option value="">待模型接入</option>}</select></div>
        <div className="field row between"><label>生成数量</label><div className="stepper"><button aria-label="减少张数" disabled={count <= 1} onClick={() => setCount(n => n - 1)}>−</button><span>{count}</span><button aria-label="增加张数" disabled={count >= selected.maxCount} onClick={() => setCount(n => n + 1)}>+</button></div></div>
        <div className="generate-area"><div className="price-row"><span>{price ? `${cash(price)} / 张 × ${count}` : '单价待公布'}</span><strong>{price ? cash(price * count) : '—'}</strong></div><button className="primary generate" disabled={busy || (user ? !quote || !prompt.trim() || (mode === 'REFERENCE' && !refs.length) : false)} onClick={generate}>{busy ? <LoaderCircle className="spin" size={18}/> : <Sparkles size={18}/>} {!user ? '登录后开始创作' : !selected.available ? '模型暂未开放' : '生成图片'}{!busy && <ArrowUpRight size={18}/>}</button><p><ShieldCheck size={12}/>成功交付后结算，失败释放金额</p></div>
      </section><section className="canvas-panel"><div className="canvas-toolbar"><div className="row"><span className="canvas-label">创作画布</span><span className="soft-badge">{tasks.length ? `${tasks.length} 个任务` : '准备就绪'}</span></div><button className="text-button" onClick={() => setTab('history')}><Clock3 size={15}/>历史记录</button></div>{tasks.length ? <div className="results-grid">{tasks.slice(0, 12).map(resultCard)}</div> : <div className="empty-canvas"><div className="canvas-frame"><span className="corner tl"/><span className="corner tr"/><span className="corner bl"/><span className="corner br"/><div className="frame-mark"><Aperture size={50} strokeWidth={1}/></div><h2>让想象，有画面。</h2><p>从一段描述，或一张参考图开始</p><div className="frame-meta">你的下一幅作品，将在这里呈现</div></div><div className="prompt-starters"><span>试试这些画面</span>{['雨后街角的咖啡馆，电影感光影', '极简香水广告，柔和侧光'].map(s => <button key={s} onClick={() => setPrompt(s)}><Plus size={14}/>{s}</button>)}</div></div>}<div className="canvas-bottom"><span><Clock3 size={13}/>作品保留 72 小时，请及时下载</span><span>多模型 · 原生尺寸</span></div></section></main> : <main className="page-content"><div className="page-heading"><div><h1>{title}</h1><p>{tab === 'history' ? '最近三天的想法，都在这里。' : tab === 'wallet' ? '每一笔花费，清楚可查。' : tab === 'admin' ? '管理模型、价格与待处理订单。' : '管理登录安全与设备会话。'}</p></div>{tab === 'history' && <button className="secondary" onClick={() => setTab('studio')}><Plus size={17}/>新建创作</button>}</div>
        {!user ? <div className="empty-page"><LockKeyhole size={32}/><h2>登录后查看{title}</h2><p>在不同设备上继续创作，查看余额与历史。</p><button className="primary" onClick={() => setAuth(true)}>登录 / 注册</button></div> : <>
          {tab === 'history' && <><div className="info-strip"><Clock3 size={17}/>图片和提示词最多保留三天，账单独立保存。</div>{tasks.length ? <div className="history-grid">{tasks.map(resultCard)}</div> : <div className="empty-page"><Images size={32}/><h2>还没有创作记录</h2><p>完成的作品会按时间出现在这里。</p><button className="secondary" onClick={() => setTab('studio')}>去创作</button></div>}</>}
          {tab === 'wallet' && <><div className="wallet-grid"><section className="wallet-card"><span>可用余额</span><div className="big-balance">{cash(balance.available)}</div><p>处理中金额 <b>{cash(balance.frozen)}</b></p><small>生成与退款处理完成后自动结算</small></section><section className="surface recharge"><h2>{demo ? '测试充值' : '账户充值'}</h2><p>{demo ? '仅用于验证流程，不会扣取真实资金。' : '支付渠道尚未开放，目前不会收取费用。'}</p><div className="amount-options">{[1000, 3000, 5000, 10000].map(a => <button key={a} onClick={() => setTopup(a)} className={topup === a ? 'selected' : ''}>{cash(a)}</button>)}</div><button className="primary" disabled={!demo || busy} onClick={() => run(async () => { const p = await api<Payment>('payments', { amount: topup, requestKey: crypto.randomUUID() }); await api('payments/test-confirm', { id: p.id }); await refreshWallet(); setNotice('测试余额已入账，没有发生真实支付'); })}>{demo ? '确认测试充值' : '充值暂未开放'}<ArrowUpRight size={16}/></button></section></div><section className="surface table-section"><h2>消费流水</h2><div className="table-scroll"><table><thead><tr><th>时间</th><th>类型</th><th>可用余额变化</th><th>处理中变化</th></tr></thead><tbody>{ledger.map(l => <tr key={l.id}><td>{time(l.createdAt)}</td><td>{ledgerNames[l.kind] || l.kind}</td><td>{l.availableDelta > 0 ? '+' : ''}{cash(l.availableDelta)}</td><td>{l.frozenDelta > 0 ? '+' : ''}{cash(l.frozenDelta)}</td></tr>)}</tbody></table>{!ledger.length && <p className="table-empty">暂无流水</p>}</div></section><section className="surface table-section"><h2>充值订单</h2>{payments.map(p => <div className="order-row" key={p.id}><div><b>{cash(p.amount)}</b><small>{time(p.createdAt)} · {p.status === 'PAID' ? '已到账' : p.status === 'REFUNDED' ? '已退款' : '待确认'}</small></div>{p.status === 'PAID' && <button className="secondary" disabled={busy || refunds.some(r => r.paymentId === p.id)} onClick={() => run(async () => { await api('refunds', { paymentId: p.id }); await refreshWallet(); setNotice('已提交退款申请，待管理员审核'); })}>{refunds.some(r => r.paymentId === p.id) ? '已申请退款' : '申请整笔退款'}</button>}{p.status === 'PENDING' && demo && <button className="secondary" onClick={() => run(async () => { await api('payments/test-confirm', { id: p.id }); await refreshWallet(); })}>确认测试到账</button>}</div>)}{!payments.length && <p className="table-empty">暂无充值订单</p>}</section></>}
          {tab === 'account' && <div className="account-grid"><section className="surface"><div className="profile"><div className="large-avatar">{user.username[0].toUpperCase()}</div><div><h2>{user.username}</h2><p>账号密码登录</p></div></div><div className="info-strip">请保管好恢复码。当前未启用短信或邮箱找回。</div><button className="secondary full" onClick={() => run(async () => { await api('auth/revoke', {}); setNotice('其他设备已退出登录'); })}>退出其他设备</button><button className="text-button danger" onClick={() => run(async () => { await api('auth/logout', {}); await refreshUser(); setNotice('已退出登录'); })}><LogOut size={16}/>退出当前账户</button></section><section className="surface"><h2>修改密码</h2><form className="stack-form" onSubmit={e => { e.preventDefault(); const body = Object.fromEntries(new FormData(e.currentTarget)); void run(async () => { const d = await api<{ recoveryCode: string }>('auth/password', body); setRecovery(d.recoveryCode); setAuth(true); }); }}><label>原密码<input name="currentPassword" type="password" autoComplete="current-password" required/></label><label>新密码<input name="password" type="password" minLength={10} maxLength={128} autoComplete="new-password" required placeholder="至少 10 位"/></label><button className="primary" disabled={busy}>更新密码</button></form></section></div>}
          {tab === 'admin' && admin && <><PoolAdmin onChange={async () => { await Promise.all([refreshAdmin(), loadModels()]); }}/><section className="surface table-section"><h2>模型与定价</h2>{admin.models.map(m => <div className="admin-model" key={m.id}><div className="row between"><b>{m.name}</b><button className="secondary" disabled={busy} onClick={() => run(async () => { await api('admin/models', { id: m.id, enabled: !m.enabled }); await Promise.all([refreshAdmin(), loadModels()]); })}>{m.enabled ? '下架' : '上架'}</button></div>{m.prices.length ? m.prices.map(p => <button className="price-chip" key={p.id} onClick={() => setPriceEdit({ model: m, price: p })}>{p.mode === 'TEXT' ? '文生图' : '图生图'} / {p.size} / {p.quality} / {cash(p.unitCents)}<Settings2 size={13}/></button>) : <p>尚未验证模型能力，暂不可定价或销售</p>}</div>)}</section><section className="surface table-section"><h2>供应渠道</h2>{admin.channels.map(c => <div className="order-row" key={c.id}><div><b>{c.name}</b><small>{c.verified ? '已验证' : '待实现与验证'}</small></div><button className="secondary" onClick={() => run(async () => { await api('admin/channels', { id: c.id, enabled: !c.enabled }); await Promise.all([refreshAdmin(), loadModels()]); })}>{c.enabled ? '停用' : '启用'}</button></div>)}</section><section className="surface table-section"><h2>退款审核</h2>{!admin.refunds.length && <p>没有待处理的退款</p>}{admin.refunds.map(r => <div className="order-row" key={r.id}><span>{cash(r.amount)} · {r.id.slice(-8)}</span><div className="row">{[true, false].map(approve => <button className="secondary" key={String(approve)} disabled={busy} onClick={() => run(async () => { await api('admin/refunds', { id: r.id, approve }); await refreshAdmin(); })}>{approve ? '批准退款' : '驳回并释放'}</button>)}</div></div>)}</section><section className="surface table-section"><h2>异常任务核查</h2>{!admin.tasks.length && <p>没有待核查任务</p>}{admin.tasks.map(t => <div className="order-row" key={t.id}><div><b>{t.modelName} · {t.id.slice(-8)}</b><small>{t.error}</small></div><button className="secondary" disabled={busy} onClick={() => run(async () => { await api('admin/tasks/resolve', { id: t.id }); await refreshAdmin(); })}>按已交付图片结算</button></div>)}</section></>}
        </>}
      </main>}
    </div>
    <Modal open={auth} onOpenChange={v => { if (!recovery) setAuth(v); }} title={recovery ? '保存你的账户恢复码' : authMode === 'register' ? '创建幻彩账户' : authMode === 'recover' ? '恢复账户' : '欢迎回到幻彩'}>{recovery ? <div className="stack-form"><p>恢复码只展示这一次。忘记密码时可用它找回账户，请保存在安全的地方。</p><code className="recovery-code">{recovery}</code><button className="secondary" onClick={() => run(async () => { await navigator.clipboard.writeText(recovery); setNotice('恢复码已复制'); })}><Copy size={16}/>复制恢复码</button><button className="primary" onClick={() => { setRecovery(''); setAuth(false); }}>我已保存</button></div> : <><p className="dialog-subtitle">继续你的创作，随时在其他设备接着完成。</p><form className="stack-form" onSubmit={submitAuth}><label>账号<input name="username" autoComplete="username" required minLength={3} maxLength={24} pattern="[a-zA-Z0-9_]+" placeholder="字母、数字或下划线"/></label>{authMode === 'recover' && <label>恢复码<input name="recoveryCode" autoComplete="off" required/></label>}<label>{authMode === 'recover' ? '新密码' : '密码'}<input name="password" type="password" minLength={10} maxLength={128} autoComplete={authMode === 'login' ? 'current-password' : 'new-password'} required placeholder="至少 10 位"/></label>{authError && <p className="form-error" role="alert">{authError}</p>}<button className="primary" disabled={busy}>{busy ? '处理中…' : authMode === 'register' ? '注册并继续' : authMode === 'recover' ? '重设密码' : '登录'}</button></form><div className="auth-links"><button onClick={() => { setAuthMode(authMode === 'register' ? 'login' : 'register'); setAuthError(''); }}>{authMode === 'register' ? '已有账户？去登录' : '创建新账户'}</button><button onClick={() => { setAuthMode(authMode === 'recover' ? 'login' : 'recover'); setAuthError(''); }}>{authMode === 'recover' ? '返回登录' : '忘记密码'}</button></div></>}</Modal>
    <Modal open={!!preview} onOpenChange={v => !v && setPreview(null)} title="图片预览">{preview && <div className="preview"><img src={`/api/assets/${preview.id}`} alt="作品大图"/><div className="row between"><span>{preview.width} × {preview.height}</span><a className="primary" href={`/api/assets/${preview.id}?download`}><Download size={16}/>下载原图</a></div></div>}</Modal>
    <Modal open={help} onOpenChange={setHelp} title="创作帮助"><div className="help-copy"><p>选择模型并描述画面，或上传参考图后说明修改方向。每个模型只显示其支持的尺寸和参数。</p><p>生成前会预留本次金额，成功交付后结算，失败部分自动释放。处理中金额可在钱包查看。</p><p>作品与提示词保留 72 小时，过期后无法恢复，请及时下载。充值与消费账单独立保存。</p>{demo && <p>当前为接口测试环境：充值不涉及真实支付；GPT Image 2 会调用已配置的真实中转接口。</p>}</div></Modal>
    <Modal open={!!priceEdit} onOpenChange={v => !v && setPriceEdit(null)} title="调整单张价格">{priceEdit && <form className="stack-form" onSubmit={e => { e.preventDefault(); const amount = Number(new FormData(e.currentTarget).get('cents')); void run(async () => { await api('admin/prices', { modelId: priceEdit.model.id, mode: priceEdit.price.mode, size: priceEdit.price.size, quality: priceEdit.price.quality, unitCents: amount }); setPriceEdit(null); await Promise.all([refreshAdmin(), loadModels()]); }); }}><p>{priceEdit.model.name} / {priceEdit.price.size} / {priceEdit.price.mode === 'TEXT' ? '文生图' : '图生图'}</p><label>价格（分）<input type="number" name="cents" min={1} max={100000} step={1} defaultValue={priceEdit.price.unitCents} required/></label><p>已受理任务保持原报价，新报价使用新价格。</p><button className="primary" disabled={busy}>保存新价格</button></form>}</Modal>
    {notice && <div className="toast" role="status">{notice}<button aria-label="关闭提示" onClick={() => setNotice('')}><X size={16}/></button></div>}
  </div>;
}
